apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.sa.name }}
  labels:
    app:  {{ .Values.global.label.name }}
    app.kubernetes.io/name: tekton-pipelinerun-cleaner
    app.kubernetes.io/component: pipelinerun-cleaner
    app.kubernetes.io/part-of: tekton
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.role.name }}
  labels:
    app: {{ .Values.global.label.name }}
    app.kubernetes.io/name: tekton-pipelinerun-cleaner
    app.kubernetes.io/component: pipelinerun-cleaner
    app.kubernetes.io/part-of: tekton
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - delete
      - get
      - watch
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.rolebinding.name }}
  labels:
    app: {{ .Values.global.label.name }}
    app.kubernetes.io/name: tekton-pipelinerun-cleaner
    app.kubernetes.io/component: pipelinerun-cleaner
    app.kubernetes.io/part-of: tekton
roleRef:
  kind: Role
  name: {{ .Values.global.role.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.sa.name }}
